name: Cache Dependencies
on:
  push:
    branches:
      - main

jobs:
  cache-dependencies:
    name: Cache dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Cache Go modules
        uses: actions/cache@3624ceb22c1c5a301c8db4169662070a689d9ea8 #v4.1.1
        with:
          path: |
            ~/.cache/go-build/
            ~/go/pkg/mod/
          key: go-${{ hashFiles('go.sum') }}
          restore-keys: |
            go-
