name: Cache Dependencies
on:
  push:
    branches:
      - main

jobs:
  cache-dependencies:
    name: Cache dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Cache Go modules
        uses: actions/cache@2cdf405574d6ef1f33a1d12acccd3ae82f47b3f2 #v4.1.0
        with:
          path: |
            ~/.cache/go-build/
            ~/go/pkg/mod/
          key: go-${{ hashFiles('go.sum') }}
          restore-keys: |
            go-
